[project]
name = "companies-watch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dmytro.v", email = "dmytro.v@ddstgroup.com" }
]
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "psycopg[binary]>=3.3.5",
    "pydantic-settings>=2.15.0",
]

[project.scripts]
companies-watch = "companies_watch:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]
